const challenges = [
    "Kill the monster",
    "Capture the monster (if applicable)",
    "Hunt the monster within 10 minutes (no capture)",
    "Complete a rampage the monster participates in",
    "Hunt the monster using the element(s) it resists",
    "Hunt the monster using one of it's weapons",
    "Hunt the monster without using healing items",
    "Hunt the monster without sharpening your weapon",
    "Hunt the monster without using silkbind moves",
    "Hunt the monster without using mountable monsters",
    "Hunt the monster using [Great Sword]",
    "Hunt the monster using [Sword and Shield]",
    "Hunt the monster using [Dual Blades]",
    "Hunt the monster using [Long Sword]",
    "Hunt the monster using [Hammer]",
    "Hunt the monster using [Hunting Horn]",
    "Hunt the monster using [Lance]",
    "Hunt the monster using [Gunlance]",
    "Hunt the monster using [Switch Axe]",
    "Hunt the monster using [Charge Blade]",
    "Hunt the monster using [Insect Glaive]",
    "Hunt the monster using [Bow]",
    "Hunt the monster using [Light Bowgun]",
    "Hunt the monster using [Heavy Bowgun]",
    "Aim for a small or large crown",
    "Take a picture of the monster",
    "Break 2+ monster parts",
    "Sever the tail (if applicable)",
    "Hunt the monster without wearing any armour",
    "Hunt a high rank monster wearing low rank armour",
];

module.exports = {challenges};
